### ISSUE TITLE
I can't restore my passwords from backup

### ISSUE THREAD

**Issue by d3d0n** [yogeshpaliyal/KeyPass#70]
Hi there, after migration from EvoX 6.0(a12) to MIUI 12.5.4.0, I don't able to restore my passwords from my backup(
That's horrible, keyphrase is correct, KeyPass just "crashing"(exits) and my passwds doesn't restoring

**Comment by yogeshpaliyal** [comment]
Hello @d3d0n 
Can you please share which version you are using earlier and which one is using now?

**Comment by KerbalNo15** [comment]
Same here, I updated with F-droid and noticed a second icon in my app drawer. I thought F-droid had installed the new version as a different app, so I uninstalled it (facepalm.) I have backups turned on, but when I select the backup file I want to restore the app just crashes. I tried restoring in the previous version as well (1.4.1) Is there a way to decrypt the backup outside of the app?

**Comment by KerbalNo15** [comment]
After building myself in Android Studio, I found out that the restore doesn't work without play services installed. I can restore in the emulator, so I'll just copy my passwords one by one from there. The restore function works beautifully on "normal" devices.

**Comment by yogeshpaliyal** [comment]
Thank you @KerbalNo15 for pointing out the issue, I will try to fix this.
Can you please send the error log also.

**Comment by KerbalNo15** [comment]
I've been trying to get an actionable error from it, but nothing shows up. Nothing gets printed to logcat when it crashes, and I can't screen record it because of security policy. I spammed breakpoints all over to see if I could pin it down. The only thing that might be related (and what makes me think it's related to play services) is the following line in logcat:

`I/EngineFactory: Provider GmsCore_OpenSSL not available`

which shows up when you open the settings window.

I attached a screenshot, but basically in app/src/main/java/com/yogeshpaliyal/keypass/ui/settings/MySettingsFragment.kt, the last breakpoint the application reaches is line 115. It does not produce an error, so the catch block is skipped. It crashes immediately when you click on a file in the file picker. onActivityResult() on line 121 is never reached.
![Screenshot from 2022-01-15 19-27-59](https://user-images.githubusercontent.com/70920991/149647596-11abbcc9-c397-4d8d-ba3d-205669640183.png)

The only error at all was when you open the settings window for the first time:

`com.yogeshpaliyal.keypass W/AndroidKeysetManager: keyset not found, will generate a new one
    java.io.FileNotFoundException: can't read keyset; the pref value __androidx_security_crypto_encrypted_prefs_key_keyset__ does not exist
        at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.readPref(SharedPrefKeysetReader.java:71)
        at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.readEncrypted(SharedPrefKeysetReader.java:89)
        at com.google.crypto.tink.KeysetHandle.read(KeysetHandle.java:105)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:311)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)`
...etc

Maybe it's just a problem with custom ROMs, which isn't really that big of a user base. I'm using Lineageos  18.1 on a Oneplus 8 (instantnoodle)

**Comment by yogeshpaliyal** [comment]
Thanks for informing I will try to replicate this and fix this asap

**Comment by yogeshpaliyal** [comment]
Thanks @KerbalNo15 for these efforts

**Comment by KerbalNo15** [comment]
You're welcome :)
